name: Monitorización Web

on:
  schedule:
    - cron: '*/10 * * * *'  # Se ejecuta cada 10 minutos
  workflow_dispatch:

jobs:
  check_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Comprobar estado de la web
        run: |
          URL="https://ejemplo.com"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          echo "$TIMESTAMP - Código: $STATUS_CODE" >> monitor.log

      - name: Guardar resultado
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add monitor.log
          git commit -m "Actualización de monitor.log"
          git push origin main
